<a href="https://colab.research.google.com/github/eildes06/Randomlyworks/blob/main/mediumnumpyex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



Numpy kutuphanesi




Standart Python listeleri dinamik olarak büyüyebilen diziler iken, NumPy dizileri oluşturulurken sabit bir boyuta sahiptir.Hatırlarsanız bir önceki yazı olan veri yapıları yazısında listelerden bahsetmiştik ve listelerde değişiklik yapabiliyorduk.Bir ndarray boyutunu değiştirdiğinizde yeni bir dizi oluşturulur ve orjinali silinir.

ndarray.ndim : Aksis (boyut) sayısını verir. Bu da “rank” olarak adlandırılır

ndarray.shape : Dizi boyutunu verir. a X b matrisi (a,b) olarak döner.
ndarray.size : Dizideki eleman sayısını verir. Yani a*b işleminin sonucudur.
ndarray.dtype : Dizideki eleman türünü döndürür.

In [3]:
import numpy as np
a= np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape # boyut

(3, 5)

In [5]:
a.ndim # rank

2

In [6]:
a.size # number of item

15

In [7]:
a.dtype.name # elaman turune dondurmek

'int64'

In [8]:
type(a) # arayin turu

numpy.ndarray

In [9]:

b = np.array([1,2,3,4,5])
b

array([1, 2, 3, 4, 5])

In [10]:
c=np.zeros((3,4))
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
d= np.ones((3,3))
d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
e = np.arange(10,70,10)
e

array([10, 20, 30, 40, 50, 60])

In [13]:
f=np.eye(3,3)
f

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
g= np.arange(0,10)
g

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
g1= np.arange(10)
g1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
h= np.linspace(0,2,9)
h

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [59]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [17]:
l=np.ones((2,4))*5
l

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [18]:
k=np.full((2,3),8)
k

array([[8, 8, 8],
       [8, 8, 8]])

In [19]:
i= np.random.randint(0,50,5)
i

array([36, 42, 18, 21, 38])

In [20]:
m= np.random.rand(5)
m

array([0.67756056, 0.81644059, 0.70843955, 0.97624078, 0.09677439])

Eleman Seçme(Indeksleme)

Genel kullanım : ndarray[rows,columns]
Not: ndarray[:,:] → buradaki “:” kullanımı tüm satır ve sütunları seçmemizi sağlar.


Array’leri [ ] ile temsil ediyoruz

In [21]:
n_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ,10, 11, 12, 13 ,14])
n_array = n_array.reshape(3,5)#array’i 3*5 formatına getirdik
n_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [23]:
n_array[0]


array([0, 1, 2, 3, 4])

In [24]:
n_array[0:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
n_array[0][0]

0

In [26]:
n_array[:,0]

array([ 0,  5, 10])

In [28]:
n_array[:,0:2]

array([[ 0,  1],
       [ 5,  6],
       [10, 11]])

In [21]:
n_array[1][4]

In [30]:
n_array[1][2]

7

In [31]:
n_array[::-1]

array([[10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

Matematiksel İşlemler

In [32]:
numpy_array = np.array([[1,2,3],
                        [4,5,6],
                        [7,8,9]])

In [33]:
numpy_array.sum()

45

In [34]:
numpy_array.max()

9

In [35]:
numpy_array.min()

1

In [36]:
numpy_array.sum(axis = 1) # satirlari toplamak

array([ 6, 15, 24])

In [37]:
numpy_array.sum(axis = 0) #sutunlari toplamak

array([12, 15, 18])

In [38]:
num_array = np.array([[1,2],
                      [5,6]])

In [39]:
num_array + num_array

array([[ 2,  4],
       [10, 12]])

In [40]:
num_array + 2

array([[3, 4],
       [7, 8]])

In [41]:
num_array - num_array

array([[0, 0],
       [0, 0]])

In [43]:
num_array * num_array

array([[ 1,  4],
       [25, 36]])

In [44]:
num_array * 3

array([[ 3,  6],
       [15, 18]])

In [45]:
num_array ** 3

array([[  1,   8],
       [125, 216]])

In [46]:
num_array / num_array

array([[1., 1.],
       [1., 1.]])

In [47]:
list_array = np.array([[1,2],
                       [4,5],
                       [7,8]])

In [48]:
list_array.T

array([[1, 4, 7],
       [2, 5, 8]])

In [62]:
num_array.mean()


3.5

In [64]:
np.median(num_array)

3.5

In [63]:
num_array.median()

AttributeError: ignored

In [65]:
num_array.var()

4.25

In [66]:
num_array.std()

2.0615528128088303

 Matris Çarpımı

In [49]:
a1 = np.array([[1,2],
               [2,0], 
               [3,1]])
a2 = np.array ([[4,3],
                [1,2]])

In [50]:
np.dot(a1,a2)

array([[ 6,  7],
       [ 8,  6],
       [13, 11]])

In [51]:
a3 = np.array([[1,2],
               [2,0],
               [3,1]])

Matris Birleştirme

In [52]:
np.concatenate([numpy_array, numpy_array], axis =0)#satira gore birlestirme

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
np.concatenate([numpy_array, numpy_array], axis =1)
#sutuna gore birlestirme

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])